apiVersion: v2
appVersion: 0.7.14
description: A centralized game library/collection management service with a focus on emulation
name: retrom
version: 2026.2.3
kubeVersion: ">=1.16.0-0"
keywords:
  - retrom
home: https://github.com/retsamedoc/helm-charts/tree/main/charts/retrom
icon: https://raw.githubusercontent.com/JMBeresford/retrom/refs/heads/main/packages/client/icons/icon.png
sources:
  - https://github.com/JMBeresford/retrom
  - https://github.com/retsamedoc/helm-charts/tree/main/charts/retrom
maintainers:
  - name: Zach Schimke
    email: retsamedoc@digitalactionsproject.org
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |-
        Upgraded the common library to v4.6.2
