#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/juicerescue/juicepassproxy
  # -- image tag
  tag: 0.5.1
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

  # If defined, will attempt to get the EnelX Server Name, IP, and Port using telnet
  #JUICEBOX_HOST: ""

  # Continually update the JuiceBox via telnet to point to JuicePass Proxy.
  #UPDATE_UDPC: true

  # This is the IP or Hostname of the machine where JuicePass Proxy is running (required if UPDATE_UDPC is set)
  #JPP_HOST: ""

  MQTT_HOST: ""
  MQTT_USER: ""
  MQTT_PASS: ""

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        targetPort: 8047
        port: 8047
